# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20161223_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
    ]
