# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20170119_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='intro',
            field=models.CharField(default='', max_length=300, verbose_name='вступление'),
            preserve_default=False,
        ),
    ]
