# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='intro_en',
            field=models.CharField(max_length=300, null=True, verbose_name='вступление'),
        ),
        migrations.AddField(
            model_name='news',
            name='intro_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='вступление'),
        ),
    ]
