# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='имя')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата события')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='порядок сортировки')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='имя')),
                ('url', models.FileField(upload_to=gallery.models.album_dir, verbose_name='фото')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='порядок сортировки')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.Album', verbose_name='альбом')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='имя')),
                ('url', models.URLField(verbose_name='url')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='порядок сортировки')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_cover', to='gallery.Photo', verbose_name='обложка'),
        ),
    ]
