# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'альбом', 'verbose_name_plural': 'альбомы'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'фото', 'verbose_name_plural': 'фото'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'видео', 'verbose_name_plural': 'видео'},
        ),
        migrations.AlterField(
            model_name='album',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='video',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='порядок сортировки'),
        ),
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together=set([('album', 'order')]),
        ),
    ]
