# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 15:16
from __future__ import unicode_literals

from django.db import migrations
import gallery.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20161221_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='original',
            field=sorl.thumbnail.fields.ImageField(upload_to=gallery.models.album_dir, verbose_name='фото'),
        ),
    ]
