# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20161222_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, unique=True, verbose_name='порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='video',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, unique=True, verbose_name='порядок сортировки'),
        ),
    ]
