# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20161223_1611'),
        ('gallery', '0007_auto_20161223_1141'),
    ]

    operations = [
    ]
