# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_merge_20161223_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'альбом', 'verbose_name_plural': 'альбомы'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'фото', 'verbose_name_plural': 'фото'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'видео', 'verbose_name_plural': 'видео'},
        ),
    ]
