# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 07:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'default_permissions': ('view', 'add', 'change', 'delete'),
                'verbose_name_plural': 'Дни периодов',
                'verbose_name': 'День периода',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'default_permissions': ('view', 'add', 'change', 'delete'),
                'verbose_name_plural': 'Потоки',
                'verbose_name': 'Поток',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название объекта')),
            ],
            options={
                'default_permissions': ('view', 'add', 'change', 'delete'),
                'verbose_name_plural': 'Объекты',
                'verbose_name': 'Объект',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('functionality', models.CharField(choices=[('tourist_information', 'Информационно-туристическая функция'), ('transportation', 'Транспортная функция'), ('language', 'Лингвистическая функцияфункция'), ('festival', 'Фестиваль болельщиков')], max_length=32, verbose_name='Функциональное направление')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='schedules.Place', verbose_name='Объект')),
            ],
            options={
                'default_permissions': ('view', 'add', 'change', 'delete'),
                'verbose_name_plural': 'Позиции',
                'verbose_name': 'Позиция',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'default_permissions': ('view', 'add', 'change', 'delete'),
                'verbose_name_plural': 'Смены',
                'verbose_name': 'Смена',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'default_permissions': ('view', 'add', 'change', 'delete'),
                'verbose_name_plural': 'Команды',
                'verbose_name': 'Команда',
            },
        ),
        migrations.CreateModel(
            name='UserPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_permanent', models.BooleanField(verbose_name='Закреплённый')),
                ('days', models.ManyToManyField(to='schedules.Day')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_positions', to='schedules.Position')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedules.Shift')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': ('view', 'add', 'change', 'delete'),
                'verbose_name_plural': 'Позиции пользователя',
                'verbose_name': 'Позиция пользователя',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='schedules.UserPosition', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedules.Period'),
        ),
        migrations.AddField(
            model_name='team',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='schedules.Place'),
        ),
        migrations.AddField(
            model_name='team',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedules.Shift'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_leader_position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_leader', to='schedules.UserPosition'),
        ),
        migrations.AddField(
            model_name='day',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='schedules.Period', verbose_name='Период'),
        ),
    ]
