# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 16:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'День потока', 'verbose_name_plural': 'Дни потоков'},
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='schedules.UserPosition', to=settings.AUTH_USER_MODEL, verbose_name='Члены команды'),
        ),
        migrations.AlterField(
            model_name='team',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedules.Period', verbose_name='Поток'),
        ),
        migrations.AlterField(
            model_name='team',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='schedules.Place', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='team',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedules.Shift', verbose_name='Смена'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_leader_position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_leader', to='schedules.UserPosition', verbose_name='Старший волонтёр'),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='days',
            field=models.ManyToManyField(to='schedules.Day', verbose_name='Дни потока'),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_positions', to='schedules.Position', verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.Team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Волонтёр'),
        ),
    ]
