# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 16:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0002_auto_20170328_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(unique=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_leader_position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='team_leader', to='schedules.UserPosition', verbose_name='Старший волонтёр'),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.Team', verbose_name='Команда'),
        ),
        migrations.AlterUniqueTogether(
            name='userposition',
            unique_together=set([('user', 'team')]),
        ),
    ]
