# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20170328_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposition',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_positions', to='schedules.Team', verbose_name='Команда'),
        ),
    ]
