# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_auto_20170329_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='system_name',
            field=models.CharField(choices=[('first', '13 – 23 июня 2018 года'), ('second', '24 июня – 4 июля 2018 года'), ('third', '5 – 15 июля 2018 года'), ('any', 'в любой указанный период')], default='', max_length=8, unique=True, verbose_name='Системное имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='system_name',
            field=models.CharField(choices=[('first', '10:00 – 16:00'), ('second', '16:00 – 22:00')], default='', max_length=8, unique=True, verbose_name='Системное имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
    ]
