# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-05 09:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_create_shifts_and_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposition',
            name='days',
            field=models.ManyToManyField(related_name='user_positions', to='schedules.Day', verbose_name='Дни потока'),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_positions', to=settings.AUTH_USER_MODEL, verbose_name='Волонтёр'),
        ),
    ]
