# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_auto_20170405_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='system_name',
            field=models.CharField(choices=[('first', '10:00 – 16:00'), ('second', '16:00 – 22:00'), ('third', '22:00 – 04:00'), ('fourth', '04:00 – 10:00'), ('fifth', '14:00 – 20:00'), ('sixth', '20:00 – 02:00')], max_length=8, unique=True, verbose_name='Системное имя'),
        ),
    ]
