# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 05:51
from __future__ import unicode_literals

from django.db import migrations

from schedules.models import Shift


def create_shifts(apps, schema_editor):
    for system_name, name in Shift.CHOICES:
        Shift.objects.get_or_create(name=name, system_name=system_name)


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_auto_20170412_0850'),
    ]

    operations = [
        migrations.RunPython(create_shifts)
    ]
