# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_create_shifts_20170412_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='system_name',
            field=models.CharField(choices=[('first', '10 – 19 июня 2018 года'), ('second', '20 июня – 29 июня 2018 года'), ('third', '30 июня – 9 июля 2018 года'), ('fourth', '10 июля – 19 июля 2018 года'), ('any', 'в любой указанный период')], max_length=8, unique=True, verbose_name='Системное имя'),
        ),
    ]
