# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 06:04
from __future__ import unicode_literals

from datetime import date, timedelta as delta

from django.db import migrations

from schedules.models import Period, Day


PERIODS_DAY_RANGE = {
    Period.FIRST: [date(2018, 6, 10) + delta(days=x) for x in range(0, 10)],
    Period.SECOND: [date(2018, 6, 20) + delta(days=x) for x in range(0, 10)],
    Period.THIRD: [date(2018, 6, 30) + delta(days=x) for x in range(0, 10)],
    Period.FOURTH: [date(2018, 7, 10) + delta(days=x) for x in range(0, 10)],
    Period.ANY: [],
}


def update_periods(apps, schema_editor):
    for system_name, name in Period.CHOICES:
        period, created = Period.objects.get_or_create(system_name=system_name)

        period.name = period.get_system_name_display()
        period.save()
        period.days.all().delete()

        for day in PERIODS_DAY_RANGE.get(period.system_name):
            Day.objects.get_or_create(period=period, date=day)


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_auto_20170412_0903'),
    ]

    operations = [
        migrations.RunPython(update_periods)
    ]
