# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-14 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_auto_20170412_0904'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userposition',
            unique_together=set([]),
        ),
    ]
