# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-21 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0012_auto_20170414_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='functionality',
            field=models.CharField(choices=[('tourist_information', 'Информационно-туристическая функция'), ('transportation', 'Транспортная функция'), ('language', 'Лингвистическая функция'), ('festival', 'Фестиваль болельщиков')], max_length=32, verbose_name='Функциональное направление'),
        ),
    ]
