# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 06:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import users.models
import volunteer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='фамилия')),
                ('middle_name', models.CharField(max_length=30, verbose_name='отчество')),
                ('gender', models.CharField(choices=[('male', 'мужчина'), ('female', 'женщина')], max_length=8, verbose_name='пол')),
                ('birthday', models.DateField(verbose_name='дата рождения')),
                ('birthplace', models.TextField(verbose_name='место рождения')),
                ('passport_number', models.PositiveSmallIntegerField(verbose_name='номер паспорта')),
                ('passport_issued', models.CharField(max_length=256, verbose_name='паспорт выдан')),
                ('passport_issued_date', models.DateField(verbose_name='дата выдачи паспорта')),
                ('registration', models.TextField(verbose_name='адрес места жительства')),
                ('residence', models.TextField(verbose_name='фактическое место жительства')),
                ('place_of_study', models.CharField(max_length=265, verbose_name='место учёбы')),
                ('speciality', models.CharField(max_length=256, verbose_name='специальность/направление подготовки, курс')),
                ('working', models.BooleanField(verbose_name='работаю')),
                ('work_place', models.CharField(max_length=256, verbose_name='место работы')),
                ('position', models.CharField(max_length=128, verbose_name='должность')),
                ('employer_phone', volunteer.fields.PhoneField(blank=True, max_length=20, verbose_name='контактный телефон работодателя')),
                ('phone', volunteer.fields.PhoneField(max_length=20, verbose_name='контактный телефон')),
                ('english', models.CharField(choices=[('elementary', 'начинающий'), ('intermediate', 'средний'), ('upper intermediate', 'выше среднего'), ('fluent', 'свободно')], max_length=32, verbose_name='владение английским языком')),
                ('other_language', models.CharField(max_length=256, verbose_name='владение другими языками')),
                ('has_volunteer_experience', models.BooleanField(verbose_name='опыт волонтёрской деятельности')),
                ('experience_in_sport_events', models.TextField(verbose_name='Спортивные мероприятия, в которых принимал участие в качестве волонтера, описание своих выполняемых функций в каждом из мероприятий')),
                ('experience_in_other_events', models.TextField(verbose_name='Иные мероприятия, в которых принимал участие в качестве волонтера, описание своих выполняемых функций в каждом из мероприятий')),
                ('attracting', models.CharField(choices=[('experience', 'получение нового опыта'), ('meeting', 'встречи с новыми людьми'), ('helping', 'возможность помогать другим'), ('contributing', 'вклад в общее дело'), ('new interesting', 'новые интересы'), ('discovery', 'открытие для себя новых сфер')], max_length=32, verbose_name='Что привлекает в волонтерской деятельности?')),
                ('lacking', models.TextField(verbose_name='Каких навыков и знаний в волонтерской деятельности не хватает?')),
                ('benefits', multiselectfield.db.fields.MultiSelectField(choices=[('command experience', 'получение нового уникального опыта и навыков работы в команде'), ('communication', 'расширение круга общения'), ('personal growth', 'личностный рост и самореализация'), ('knowledge', 'расширение интересов и знаний'), ('relation', 'новые связи и потенциальные возможности'), ('foreign language', 'практика иностранных языков и широкое межкультурное общение'), ('see event inside', 'шанс увидеть мероприятие изнутри'), ('part of', 'возможность почувствовать себя значимой частью мега-события'), ('opportunity', 'открытие новых перспектив'), ('acceptance', 'признание окружающих'), ('respect', 'гордость и уважение близких')], max_length=140, verbose_name='Что Вы хотите получить от участия в качестве городского волонтера в Чемпионате мира по футболу FIFA 2018 в России?')),
            ],
            options={
                'verbose_name': 'профиль пользователя',
                'verbose_name_plural': 'профили пользователей',
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
