# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161213_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='working',
            new_name='is_working',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_studying',
            field=models.BooleanField(default=False, verbose_name='учусь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='place_of_study',
            field=models.CharField(blank=True, max_length=265, verbose_name='место учёбы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='speciality',
            field=models.CharField(blank=True, max_length=256, verbose_name='специальность/направление подготовки, курс'),
        ),
    ]
