# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20161214_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='evaluationCommunicability',
            new_name='evaluation_communicability',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='evaluationDiligence',
            new_name='evaluation_diligence',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='evaluationGoodwill',
            new_name='evaluation_goodwill',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='evaluationResponsibility',
            new_name='evaluation_responsibility',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='evaluationStressResistance',
            new_name='evaluation_stress_resistance',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='evaluationTeamworkSkills',
            new_name='evaluation_teamwork_skills',
        ),
    ]
