# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20161215_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='has_сar',
            new_name='has_car',
        ),
    ]
