# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20161215_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='evaluation_communicability',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='коммуникабельность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='evaluation_diligence',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='исполнительность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='evaluation_goodwill',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='доброжелательность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='evaluation_responsibility',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='ответственность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='evaluation_stress_resistance',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='стрессоустойчивость'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='evaluation_teamwork_skills',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='умение работать в команде'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interesting_festival',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='фестиваль болельщиков FIFA'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interesting_language',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='лингвистическая служба'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interesting_tourist_information',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='информационно-туристическая служба'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interesting_transportation',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='транспортная служба'),
        ),
    ]
