# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20161215_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='user/photo/', verbose_name='фото')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_attachments', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'анкета пользователя', 'verbose_name_plural': 'анкеты пользователей'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
