# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 12:41
from __future__ import unicode_literals

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20161216_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileattachment',
            options={'verbose_name': 'файл анкеты пользователя', 'verbose_name_plural': 'файлы анкет пользователей'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='car_detail',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='категория водительского удостоверения и стаж вождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employer_phone',
            field=core.fields.PhoneField(blank=True, max_length=20, null=True, verbose_name='контактный телефон работодателя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience_in_other_events',
            field=models.TextField(blank=True, null=True, verbose_name='иные мероприятия, в которых принимал участие в качестве волонтера, описание своих выполняемых функций в каждом из мероприятий'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience_in_sport_events',
            field=models.TextField(blank=True, null=True, verbose_name='спортивные мероприятия, в которых принимал участие в качестве волонтера, описание своих выполняемых функций в каждом из мероприятий'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='other_language',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='владение другими языками'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='place_of_study',
            field=models.CharField(blank=True, max_length=265, null=True, verbose_name='место учёбы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='speciality',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='специальность/направление подготовки, курс'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_place',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='место работы'),
        ),
    ]
