# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20161216_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='должность'),
        ),
    ]
