# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20161216_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileattachment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_attachment', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
