# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20161216_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст')),
                ('is_approve', models.BooleanField(default=False, verbose_name='утверждено')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='коментарий администратора')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='users.Profile', verbose_name='пользователь')),
            ],
        ),
    ]
