# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='is_approve',
        ),
        migrations.AddField(
            model_name='story',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='опубликовано'),
        ),
    ]
