# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20161227_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='about_yourself',
            field=models.CharField(default='', max_length=1024, verbose_name='о себе'),
            preserve_default=False,
        ),
    ]
