# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_story_about_yourself'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'анкета пользователя', 'verbose_name_plural': 'анкеты пользователей'},
        ),
        migrations.AlterModelOptions(
            name='profileattachment',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'файл анкеты пользователя', 'verbose_name_plural': 'файлы анкет пользователей'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'волонтёрская история', 'verbose_name_plural': 'волонтёрские истории'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
