# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20161228_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('inspection', 'на рассмотрении'), ('working', 'в работе'), ('approved', 'утверждено')], default='inspection', max_length=10, verbose_name='статус'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='время обновления'),
        ),
        migrations.AddField(
            model_name='profilecomment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.Profile', verbose_name='анкета'),
        ),
    ]
