# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20170117_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('inspection', 'на рассмотрении'), ('working', 'на доработке'), ('approved', 'утверждено')], default='inspection', max_length=10, verbose_name='статус'),
        ),
    ]
