# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20170119_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='about_yourself_en',
            field=models.CharField(max_length=1024, null=True, verbose_name='о себе'),
        ),
        migrations.AddField(
            model_name='story',
            name='about_yourself_ru',
            field=models.CharField(max_length=1024, null=True, verbose_name='о себе'),
        ),
        migrations.AddField(
            model_name='story',
            name='text_en',
            field=models.TextField(null=True, verbose_name='текст'),
        ),
        migrations.AddField(
            model_name='story',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='текст'),
        ),
    ]
