# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 12:15
from __future__ import unicode_literals

from django.db import migrations

from permissions import DEFAULT_GROUP


def set_default_user_group(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Group = apps.get_model('auth', 'Group')
    users_without_group = User.objects.filter(groups=None)
    volunteer_group = Group.objects.get(name=DEFAULT_GROUP)
    volunteer_group.user_set.set(users_without_group)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_role'),
        ('permissions', '0002_group_change'),
    ]

    operations = [
        migrations.RunPython(set_default_user_group)
    ]
