# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20170203_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilecomment',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'Комментарий к анкете', 'verbose_name_plural': 'Комментарии к анкете'},
        ),
    ]
