# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20170227_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('registered', 'Зарегистрированный пользователь'), ('candidate', 'Кандидат в волонтёры'), ('approved', 'Утверждённый кандидат в волонтёры'), ('tested', 'Кандидат в волонтеры, прошедший тестирование'), ('interviewed', 'Кандидат в волонтеры, прошедший отборочные процедуры'), ('prepared', 'Подготовленный кандидат в волонтеры'), ('main', 'Волонтер основного состава'), ('reserved', 'Волонтер резерва')], default='registered', max_length=12, verbose_name='роль'),
        ),
    ]
