# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_story_image'),
        ('users', '0022_auto_20170227_1500'),
    ]

    operations = [
    ]
