# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20170301_1444'),
        ('users', '0023_merge_20170227_1628'),
    ]

    operations = [
    ]
