# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_merge_20170302_1527'),
        ('users', '0024_merge_20170301_1458'),
    ]

    operations = [
    ]
