# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_set_tested_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shoe_size',
            field=models.PositiveSmallIntegerField(choices=[(34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47')], verbose_name='размер обуви'),
        ),
    ]
