# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='рейтинг пользователя'),
        ),
    ]
