# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 08:58
from __future__ import unicode_literals

from django.db import migrations

from schedules.models import Shift, Period
from users.models import Profile


def migrate_work_period_and_shift(apps, schema_editor):
    for shift in Shift.objects.all():
        profiles = Profile.objects.filter(work_shift=shift.system_name)
        profiles.update(work_shift_new=shift)

    for period in Period.objects.all():
        profiles = Profile.objects.filter(work_period=period.system_name)
        profiles.update(work_period_new=period)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20170404_1157'),
        ('schedules', '0006_create_shifts_and_periods'),
    ]

    operations = [
        migrations.RunPython(migrate_work_period_and_shift)
    ]
