# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-05 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_work_period_and_shift_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='work_period',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_shift',
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_period_new',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedules.Period', verbose_name='период работы во время чемпионата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_shift_new',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedules.Shift', verbose_name='смена работы во время чемпионата'),
            preserve_default=False,
        ),
    ]
