# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_work_period_and_shift_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='work_period',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_shift',
        ),
    ]
