# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-05 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20170405_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='work_period_new',
            new_name='work_period',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='work_shift_new',
            new_name='work_shift',
        ),
    ]
