# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_create_shifts_and_periods'),
        ('users', '0029_auto_20170404_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='work_period_new',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_shift_new',
        ),
        migrations.AddField(
            model_name='profile',
            name='work_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedules.Period', verbose_name='период работы во время чемпионата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='work_shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedules.Shift', verbose_name='смена работы во время чемпионата'),
            preserve_default=False,
        ),
    ]
