# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20170405_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.Story', verbose_name='волонтёрская история')),
            ],
            options={
                'verbose_name': 'комментарий волонтёрской истории',
                'verbose_name_plural': 'комментарии волонтёрских историй',
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
    ]
