# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 07:30
from __future__ import unicode_literals

from django.db import migrations


def migrate_user_story_comment(apps, schema_editor):
    Story = apps.get_model("users", "Story")
    StoryComment = apps.get_model("users", "StoryComment")

    for story in Story.objects.filter(is_public=False):
        if story.admin_comment:
            StoryComment.objects.create(story=story, text=story.admin_comment)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_storycomment'),
    ]

    operations = [
        migrations.RunPython(migrate_user_story_comment)
    ]
