# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20170407_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='admin_comment',
        ),
    ]
