# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-07 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_remove_story_admin_comment'),
        ('users', '0027_auto_20170407_1038'),
    ]

    operations = [
    ]
