# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-11 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20170407_1143'),
        ('users', '0034_merge_20170407_1304'),
    ]

    operations = [
    ]
