# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 12:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('period', models.CharField(choices=[(1, '09-10'), (2, '10-11'), (3, '11-12'), (4, '12-13'), (5, '13-14'), (6, '14-15'), (7, '15-16'), (8, '16-17'), (9, '17-18')], max_length=5, verbose_name='Время интервью')),
                ('status', models.CharField(choices=[('wait', 'Ожидает подтверждения'), ('reject', 'Волонтер отказался'), ('confirm', 'Волонтер согласился'), ('happen', 'Состоялось'), ('cancel', 'Не состоялось')], max_length=8, verbose_name='Статус')),
            ],
            options={
                'verbose_name_plural': 'Интервью',
                'verbose_name': 'Интервью',
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
            ],
            options={
                'verbose_name_plural': 'Интервьюеры',
                'verbose_name': 'Интервьюер',
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='interviews.Interviewer', verbose_name='Интервьюер'),
        ),
        migrations.AddField(
            model_name='interview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
