# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_auto_20170222_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('wait', 'Ожидает подтверждения'), ('reject', 'Волонтер отказался'), ('confirm', 'Волонтер согласился'), ('happen', 'Состоялось'), ('cancel', 'Не состоялось')], default='wait', max_length=8, verbose_name='Статус'),
        ),
    ]
