# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_auto_20170228_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ('date',), 'verbose_name': 'Интервью', 'verbose_name_plural': 'Интервью'},
        ),
    ]
