# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 07:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_auto_20170228_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
