# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_auto_20170228_1422'),
        ('interviews', '0005_auto_20170301_1005'),
    ]

    operations = [
    ]
