# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'статическая страница', 'verbose_name_plural': 'статические страницы'},
        ),
    ]
