# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0003_auto_20170119_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='заголовок в URL'),
        ),
    ]
