# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 09:37
from __future__ import unicode_literals
from django.db import migrations


def slug_data_migration(apps, schema_editor):
    Page = apps.get_model("static", "Page")
    for iter_num, page in enumerate(Page.objects.all()):
        page.slug = page.title.split()[0] + str(iter_num)
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0004_page_slug'),
    ]

    operations = [
        migrations.RunPython(slug_data_migration)
    ]
