# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0005_slug_data_migration_20170215_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='заголовок в URL'),
            preserve_default=False,
        ),
    ]
