# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='заголовок')),
                ('description', models.TextField(verbose_name='описание')),
                ('address', models.CharField(max_length=512, verbose_name='адрес')),
                ('start', models.DateTimeField(verbose_name='начало мероприятия')),
                ('end', models.DateTimeField(verbose_name='окончание мероприятия')),
                ('user_count', models.PositiveSmallIntegerField(verbose_name='количество участников')),
            ],
            options={
                'ordering': ('start',),
                'verbose_name_plural': 'мероприятия',
                'verbose_name': 'мероприятие',
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
    ]
