# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address_en',
            field=models.CharField(max_length=512, null=True, verbose_name='адрес'),
        ),
        migrations.AddField(
            model_name='event',
            name='address_ru',
            field=models.CharField(max_length=512, null=True, verbose_name='адрес'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='опубликовано'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='заголовок'),
        ),
    ]
