# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170323_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user_count',
            new_name='participants_number',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='volunteer_count',
            new_name='volunteer_number',
        ),
        migrations.AlterField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('participant', 'участник'), ('volunteer', 'волонтер')], max_length=16, verbose_name='статус в мероприятии'),
        ),
    ]
