# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170324_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='status',
        ),
        migrations.AddField(
            model_name='event',
            name='participants_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='количество записавшихся участников'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='volunteers_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='количество записавшихся волонтеров'),
            preserve_default=False,
        ),
    ]
