# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170324_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants_number',
        ),
        migrations.RemoveField(
            model_name='event',
            name='volunteer_number',
        ),
        migrations.AddField(
            model_name='event',
            name='participants_limit',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='максимальное количество участников'),
        ),
        migrations.AddField(
            model_name='event',
            name='volunteer_limit',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='максимальное количество волонтеров'),
        ),
        migrations.AddField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('volunteer', 'волонтёр'), ('participant', 'участник')], default='participant', max_length=16, verbose_name='статус участника'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='количество записавшихся участников'),
        ),
        migrations.AlterField(
            model_name='event',
            name='volunteers_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='количество записавшихся волонтеров'),
        ),
    ]
