# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-11 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170331_1530'),
        ('events', '0008_participation_is_done'),
    ]

    operations = [
    ]
