# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_merge_20170411_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participation',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'участие в мероприятии', 'verbose_name_plural': 'участие в мероприятиях'},
        ),
    ]
