# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 07:56
from __future__ import unicode_literals

from django.db import migrations


def create_groups(apps, schema_editor):
    group_names = (
        'Волонтёр', 'Старший волонтёр', 'Координатор', 'Сотрудник',
        'Администратор'
    )

    Group = apps.get_model("auth", "Group")
    for group_name in group_names:
        Group.objects.create(name=group_name)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
