# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='default', max_length=200, verbose_name='имя'),
        ),
    ]
