# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 08:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HallOfFame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликованно')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_of_fame', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Записи в доске почета',
                'verbose_name': 'Запись в доске почета',
            },
        ),
    ]
