# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_of_fame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='halloffame',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='halloffame',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
