# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-19 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall_of_fame', '0002_auto_20170407_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halloffame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_of_fame', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Пользователь'),
        ),
    ]
