# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 12:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(verbose_name='Правильность ответа')),
            ],
            options={
                'verbose_name_plural': 'Варианты ответа',
                'verbose_name': 'Вариант ответа',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Текст вопроса')),
            ],
            options={
                'verbose_name_plural': 'Вопросы',
                'verbose_name': 'Вопрос',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название задания')),
                ('questions_number', models.IntegerField(verbose_name='Количество вопросов')),
                ('expert_appraisal', models.BooleanField(verbose_name='Проверяется администратором')),
            ],
            options={
                'verbose_name_plural': 'Задания',
                'verbose_name': 'Задание',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название теста')),
                ('time_available', models.IntegerField(verbose_name='Доступное время')),
            ],
            options={
                'verbose_name_plural': 'Тесты',
                'verbose_name': 'Тест',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.NullBooleanField(verbose_name='Правльность ответов')),
                ('answers', models.ManyToManyField(to='user_tests.AnswerOptions', verbose_name='Ответы')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_tests.Question', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Ответы пользователей',
                'verbose_name': 'Ответы пользователя',
            },
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Время начала тестирования')),
                ('finished_at', models.DateTimeField(auto_now_add=True, verbose_name='Время окончания тестирования')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_tests.Test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Тесты пользователя',
                'verbose_name': 'Тест пользователя',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_tests.Test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='question',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_tests.Task', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='answeroptions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_tests.Question', verbose_name='Вопрос'),
        ),
    ]
