# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeroptions',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответа'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'Ответы пользователя', 'verbose_name_plural': 'Ответы пользователей'},
        ),
        migrations.AlterModelOptions(
            name='usertest',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'Тест пользователя', 'verbose_name_plural': 'Тесты пользователя'},
        ),
    ]
