# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroptions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='user_tests.Question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='task',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Аудиофайл'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
