# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='audio',
            field=models.FileField(null=True, upload_to='', verbose_name='Аудиофайл'),
        ),
        migrations.AddField(
            model_name='task',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
