# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0002_auto_20170207_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswerValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_values', models.TextField(verbose_name='Значение ответа пользователя')),
            ],
            options={
                'verbose_name_plural': 'Значения ответов пользователя',
                'default_permissions': ('view', 'add', 'change', 'delete'),
                'verbose_name': 'Значение ответа',
            },
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='answers',
        ),
        migrations.AddField(
            model_name='useranswervalue',
            name='user_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_tests.UserAnswer', verbose_name='Ответы пользователя'),
        ),
    ]
