# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0002_auto_20170202_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answeroptions',
            old_name='name',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название теста'),
        ),
    ]
