# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0003_auto_20170307_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='CattellOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(verbose_name='Номер вопроса')),
                ('factor', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('MD', 'MD')], max_length=2, verbose_name='Психологический фактор')),
                ('answer_options', multiselectfield.db.fields.MultiSelectField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c')], max_length=1, verbose_name='Варианты ответа в ключе')),
            ],
        ),
        migrations.CreateModel(
            name='CattelSten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sten', models.IntegerField(verbose_name='Количество стенов')),
                ('factor', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('MD', 'MD')], max_length=2, verbose_name='Психологический фактор')),
                ('score', models.IntegerField(verbose_name='Количество сырых баллов')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='user_tests.Task', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='user_tests.Test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='user_tests.Question', verbose_name='Вопрос'),
        ),
    ]
