# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0003_auto_20170208_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания тестирования'),
        ),
    ]
