# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0004_auto_20170314_1233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CattelSten',
            new_name='CattellSten',
        ),
    ]
