# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 05:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_tests', '0004_auto_20170209_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswervalue',
            old_name='answers_values',
            new_name='answer_value',
        ),
        migrations.AlterField(
            model_name='test',
            name='time_available',
            field=models.IntegerField(verbose_name='Доступное время в секундах'),
        ),
        migrations.AlterField(
            model_name='useranswervalue',
            name='user_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_values', to='user_tests.UserAnswer', verbose_name='Ответы пользователя'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=set([('user', 'question')]),
        ),
        migrations.AlterUniqueTogether(
            name='usertest',
            unique_together=set([('user', 'test')]),
        ),
    ]
