# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0005_auto_20170314_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('verbal', 'Вербальный'), ('numerical', 'Числовой'), ('psychological', 'Психологический'), ('foreign', 'Иностранный язык')], default='verbal', max_length=16, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название'),
        ),
    ]
