# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0005_auto_20170213_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswervalue',
            old_name='answer_value',
            new_name='value',
        ),
    ]
