# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 16:41
from __future__ import unicode_literals

from django.db import migrations

from user_tests.models import Test


def test_type_data_migration(apps, schema_editor):
    Test.objects.filter(name='verbal').update(type=Test.TYPE_VERBAL)
    Test.objects.filter(name='numerical').update(type=Test.TYPE_NUMERICAL)
    Test.objects.filter(name='psychological').update(
        type=Test.TYPE_PSYCHOLOGICAL)
    Test.objects.filter(name__in=('it', 'fr', 'de', 'en', 'es')).update(
        type=Test.TYPE_FOREIGN_LANGUAGE)


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0006_auto_20170314_1940'),
    ]

    operations = [
        migrations.RunPython(test_type_data_migration)
    ]
