# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 05:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0007_test_type_data_20170314_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
