# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 13:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_tests', '0007_auto_20170216_1146'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='useranswer',
            index_together=set([('user', 'question')]),
        ),
        migrations.AlterIndexTogether(
            name='usertest',
            index_together=set([('user', 'test')]),
        ),
    ]
