# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0008_auto_20170315_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cattelloptions',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'Вариант ответа Каттелла', 'verbose_name_plural': 'Варианты ответов Каттелла'},
        ),
        migrations.AlterModelOptions(
            name='cattellsten',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'Стен Каттелла', 'verbose_name_plural': 'Стены Каттелла'},
        ),
    ]
