# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0009_auto_20170315_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='audio',
        ),
    ]
