# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0010_remove_task_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroptions',
            name='number',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('c', 'c')], max_length=1, null=True, verbose_name='Номер ответа'),
        ),
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер вопроса'),
        ),
        migrations.AddField(
            model_name='test',
            name='is_limited',
            field=models.BooleanField(default=True, verbose_name='Ограничение времени прохождения теста'),
        ),
    ]
