# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 15:34
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0011_auto_20170316_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattelloptions',
            name='answer_options',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c')], max_length=8, verbose_name='Варианты ответа в ключе'),
        ),
    ]
