# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 08:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('event', 'мероприятие'), ('profilecomment', 'profile comment')], max_length=32, verbose_name='тип')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Баджеты',
                'default_permissions': ('view', 'add', 'change', 'delete'),
                'verbose_name': 'Баджет',
            },
        ),
    ]
