# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='type',
            field=models.CharField(choices=[('event', 'Мероприятие'), ('notice', 'Нотификация'), ('profile_comment', 'Комментарий к профилю'), ('story_comment', 'Комментарий к волонтёрской истории')], max_length=32, verbose_name='тип'),
        ),
    ]
