# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_merge_20170301_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='type',
            field=models.CharField(choices=[('notice', 'нотификация'), ('profilecomment', 'Комментарий к анкете'), ('storycomment', 'комментарий волонтёрской истории')], max_length=32, verbose_name='тип'),
        ),
    ]
